# Gradle
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Kotlin
kotlin.code.style=official
kotlin.native.binary.memoryModel=experimental
kotlin.mpp.androidSourceSetLayoutVersion=2

# Avoid Compose native compiler caching init that can fail with ArrayStoreException (KonanTarget)
compose.kotlin.native.manageCacheKind=false

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.experimental.lint.missingBaselineIsEmptyBaseline=true

# Compose
org.jetbrains.compose.experimental.uikit.enabled=true
